site_name: Container-Native Storage Hands-on Lab - Storage SA Summit 2017
site_url: 'https://dmesser.github.io/cns-lab-sa-summit/'
site_favicon: 'img/favicon.ico'
copyright: 'Copyright Â©2017 Red Hat, Inc.'

theme: 'material'
extra:
  logo: 'img/RedHat.svg'

pages:
- Overview: index.md
- Modules:
    - 'Module 1 - OpenShift in 5 Minutes': module-1-ocp-in-5.md
    - 'Module 2 - Deploying Container-Native Storage': module-2-deploy-cns.md
    - 'Module 3 - Using Persistent Storage': module-3-using-cns.md
    - 'Module 4 - Cluster Operations': module-4-cluster-ops.md
    - 'Module 5 - Advanced Topics': module-5-advanced.md

markdown_extensions:
    - smarty
    - toc:
        permalink: '#'
    - sane_lists
    - footnotes
    - smart_strong
    - nl2br
    - codehilite:
        guess_lang: False
    - admonition
